### ISSUE TITLE
Add default category "other" to the categories

### ISSUE THREAD

**Issue by brokelyn** [nilsalm/satsuma#34]
At the moment you always need to select a category when adding something to the shopping list.
Would be nice if there would be a default category like "other" where items go in otherwise

**Comment by nilsalm** [comment]
I was wondering if maybe the `category` should be optional instead, so if the `item` does not have one it shows up under "others".
On the other hand, this could lead to adding items without category and then wanting to add them to a category later, while would need a neat UX flow. At least something to think about.

**Comment by brokelyn** [comment]
Already implemented
