### ISSUE TITLE
Remove Category-page under /profile

### ISSUE THREAD

**Issue by nilsalm** [nilsalm/satsuma#38]
In /profile, there should be a link to /categories.
In /categories the categories should be lists (as in /profile as of now).
There should also be a way to edit the name of the category, could be as a seperate page /categories/:id/edit but probably would be easier to just embed a form in each `category`component in the list.

**Comment by brokelyn** [comment]
yes agree. Though it could be also where it is now and just get another header. That would keep the simplicity

**Comment by nilsalm** [comment]
Sure, for now it could live in /profile but maybe we want to add other profile-related stuff there soon, like change password, change username etc etc, then categories should get their own page i think

**Comment by brokelyn** [comment]
this will be fixed in #59
